export type Level = 'High'|'Medium'|'Low'|'Unassessed';
export type Country = {code:string;name:string;region:string;level:Level;confidence:string;headline:string;coordinates:[number,number];technologies:string[];watch:string[];customers:string[]};
export type Article = {id:string;title:string;date:string;publisher:string;kind:string;countries:string[];technology:string;summary:string;implication:string;url:string;group:string};
export const snapshot='2026-09-12';
export const regions=['APJC','Middle East','Africa','Europe','Latin America'];
export const technologies=['Enterprise campus','Data center','Full-stack AI','AI silicon','Network security','Service provider','Political'];
export const countries:Country[]=[
 {code:'CN',name:'China',region:'APJC',level:'High',confidence:'High',headline:'Dense AI, silicon and developer-platform activity.',coordinates:[104,35],technologies:['AI silicon','Full-stack AI','Data center'],watch:['Ascend ecosystem depth and availability','Agentic platforms moving from beta to production','Export-control and procurement exposure'],customers:['China-based enterprise and public-sector references are not counted as named wins in this corpus']},
 {code:'ID',name:'Indonesia',region:'APJC',level:'High',confidence:'High',headline:'Campus, fabric and AI narratives converging in market.',coordinates:[118,-3],technologies:['Enterprise campus','Data center','Full-stack AI'],watch:['Huawei Networking Solutions Group activity','DANA and partner reference context','Local AI infrastructure requirements'],customers:['DANA (reference in Huawei launch material)','Huawei partner ecosystem']},
 {code:'MY',name:'Malaysia',region:'APJC',level:'High',confidence:'Medium',headline:'Active partner and AI ecosystem signaling.',coordinates:[102,4],technologies:['Full-stack AI','Enterprise campus','Data center'],watch:['M360 / WAIC ecosystem activity','Partner-led campus transformation','Data-center and sovereign-AI buying centers'],customers:['M360 / Huawei partner ecosystem']},
 {code:'TH',name:'Thailand',region:'APJC',level:'High',confidence:'Medium',headline:'AI and campus conversations visible, buyer evidence thinner.',coordinates:[101,15],technologies:['Full-stack AI','Enterprise campus'],watch:['AI summit commitments vs deployed services','Channel-led enterprise traction','Cloud residency requirements'],customers:[]},
 {code:'SG',name:'Singapore',region:'APJC',level:'Low',confidence:'Medium',headline:'Selective service-provider and ecosystem signals.',coordinates:[103.8,1.3],technologies:['Service provider','Data center'],watch:['Singtel relationship scope','Data-center partnership announcements','Regional HQ influence'],customers:['Singtel (roundtable / ecosystem reference, not a new win)']},
 {code:'EG',name:'Egypt',region:'Africa',level:'High',confidence:'Medium',headline:'Reported AI infrastructure bid makes procurement status a live watch item.',coordinates:[30.8,26.8],technologies:['AI silicon','Data center','Political'],watch:['Whether the reported bid becomes an award','Ascend supply and integration scope','US / China policy impact on delivery'],customers:['Egyptian government (reported proposal; award not confirmed)']},
 {code:'ZA',name:'South Africa',region:'Africa',level:'High',confidence:'High',headline:'Broad campus, fabric and security portfolio push.',coordinates:[24,-29],technologies:['Enterprise campus','Data center','Network security'],watch:['SaaS campus operating model','AI-ready fabric positioning','Rain and other installed-base references'],customers:['Rain (network deployment reference)','HNS Group / Huawei ecosystem']},
 {code:'NG',name:'Nigeria',region:'Africa',level:'High',confidence:'High',headline:'Local cloud and agentic AI proposition has strong strategic fit.',coordinates:[8,9],technologies:['Full-stack AI','Data center','Service provider'],watch:['Sovereign AI data-residency demand','Government and financial-services adoption','Local partner delivery capacity'],customers:['Finance, carrier and government sectors named as target segments; no named win verified']},
 {code:'KE',name:'Kenya',region:'Africa',level:'Medium',confidence:'Medium',headline:'Fintech and AI ecosystem presence; current buyer evidence limited.',coordinates:[37,.4],technologies:['Full-stack AI','Service provider'],watch:['Event participants vs buying organizations','Cloud and security attach','Public-sector procurement signals'],customers:[]},
 {code:'MA',name:'Morocco',region:'Africa',level:'Unassessed',confidence:'Limited',headline:'Insufficient current admissible enterprise evidence in this corpus.',coordinates:[-7,32],technologies:['Enterprise campus','Data center'],watch:['Verify official enterprise account ownership','Track local partner announcements','Separate consumer and enterprise activity'],customers:[]},
 {code:'SA',name:'Saudi Arabia',region:'Middle East',level:'High',confidence:'High',headline:'Indoor connectivity and storage references show enterprise depth.',coordinates:[45,24],technologies:['Service provider','Data center','Enterprise campus'],watch:['TAWAL indoor-building solution scope','stc storage deployment context','AI infrastructure procurement'],customers:['TAWAL (indoor building solutions partnership)','stc (storage deployment reference)']},
 {code:'AE',name:'United Arab Emirates',region:'Middle East',level:'Medium',confidence:'Medium',headline:'Channel and cloud ecosystem signals; direct wins need validation.',coordinates:[54,24],technologies:['Full-stack AI','Enterprise campus','Data center'],watch:['Channel incentives and partner breadth','Sovereign AI / cloud requirements','Government account evidence'],customers:['Enterprise Systems (channel event reference)']},
 {code:'QA',name:'Qatar',region:'Middle East',level:'Unassessed',confidence:'Limited',headline:'Only historical infrastructure context admitted; current evidence gap.',coordinates:[51.2,25.3],technologies:['Data center','Enterprise campus'],watch:['Refresh local enterprise source coverage','Check current service-provider announcements','Do not infer inactivity from the gap'],customers:[]},
 {code:'DE',name:'Germany',region:'Europe',level:'Medium',confidence:'High',headline:'HPC and AI research signals, with policy context.',coordinates:[10.5,51],technologies:['Data center','Full-stack AI','Political'],watch:['Research consortium to production path','EU supply-chain policy implications','Public-sector and industrial references'],customers:['EXIGENCE research consortium (research reference)']},
 {code:'FR',name:'France',region:'Europe',level:'Medium',confidence:'High',headline:'AI data-center and research ecosystem activity.',coordinates:[2.2,46],technologies:['Data center','Full-stack AI','Political'],watch:['AIDC / compute facility scope','Research partnerships vs production','EU procurement and supply-chain debate'],customers:['EXIGENCE research consortium (research reference)']},
 {code:'ES',name:'Spain',region:'Europe',level:'Low',confidence:'Medium',headline:'Research and skills activity; limited current deployment evidence.',coordinates:[-4,40],technologies:['Full-stack AI','Political'],watch:['6G research outcomes','Local enterprise customer proof','Skills programs vs commercial pull'],customers:['EXIGENCE research consortium (research reference)']},
 {code:'TR',name:'Türkiye',region:'Europe',level:'Medium',confidence:'Limited',headline:'Skills and ecosystem activity merits validation.',coordinates:[35,39],technologies:['Enterprise campus','Full-stack AI'],watch:['Local partner and public-sector signals','Enterprise reference quality','Data-residency and sovereignty needs'],customers:[]},
 {code:'BR',name:'Brazil',region:'Latin America',level:'Medium',confidence:'High',headline:'AI-ready fabric narrative and public-sector tenders.',coordinates:[-52,-12],technologies:['Data center','Enterprise campus','Political'],watch:['CPTM tender outcome and scope','Fabric deployments beyond launch events','Public-sector maintenance vs new equipment'],customers:['CPTM (tender / maintenance context; not treated as new win)']},
 {code:'MX',name:'Mexico',region:'Latin America',level:'Medium',confidence:'High',headline:'University and public-sector infrastructure activity.',coordinates:[-102,24],technologies:['Data center','Enterprise campus'],watch:['UJED academic AI program','Pemex maintenance scope','Partner-led expansion'],customers:['UJED (academic reference)','Pemex (maintenance reference; not a new win)']},
 {code:'CO',name:'Colombia',region:'Latin America',level:'High',confidence:'Medium',headline:'Regional AI-ready networking launch raises competitive visibility.',coordinates:[-74,4.5],technologies:['Data center','Enterprise campus','Full-stack AI'],watch:['Local buyer evidence after HNS launch','AI fabric attach to campus','Channel and services execution'],customers:['HNS Group / Huawei ecosystem']}
];
export const articles:Article[]=[
 {id:'egypt-ai-bid',title:'Egypt AI infrastructure bid brings US–China competition into focus',date:'2026-08-26',publisher:'EnterpriseAM, citing Bloomberg',kind:'Reported bid',countries:['EG','CN'],technology:'AI silicon',summary:'Bloomberg reporting, relayed by EnterpriseAM, describes a Huawei proposal for Egyptian government AI training and inference infrastructure. No award is confirmed in the reviewed evidence.',implication:'Engage early on the complete AI architecture; establish procurement status before treating this as a competitive loss.',url:'https://enterpriseam.com/egypt/2026/08/26/huawei-is-bidding-to-supply-egypts-ai-infrastructure-washington-is-trying-to-stop-it/',group:'egypt-bid'},
 {id:'nigeria-agentic-cloud',title:'Nigeria: local cloud expands into agentic AI',date:'2026-08-27',publisher:'Huawei Cloud',kind:'Product announcement',countries:['NG'],technology:'Full-stack AI',summary:'Huawei announced Agentic AI Cloud in Lagos on August 27, targeting finance, carriers and government. It positions local data residency and low latency as differentiators.',implication:'Qualify sovereign-AI requirements alongside network, security and observability decisions.',url:'https://www.huaweicloud.com/intl/en-us/news/20260828180025243.html',group:'ng-cloud'},
 {id:'tawal-indoor',title:'TAWAL and Huawei deepen Saudi indoor network partnership',date:'2026-09-10',publisher:'Huawei',kind:'Partnership',countries:['SA'],technology:'Service provider',summary:'TAWAL and Huawei signed an indoor building solutions agreement covering development, market expansion and delivery. This is a partnership announcement, not a disclosed order value.',implication:'Track enterprise building connectivity projects and how cellular and Wi-Fi requirements are packaged.',url:'https://www.huawei.com/en/news/2026/9/lampsite-tawal-saudi',group:'sa-indoor'},
 {id:'stc-storage',title:'stc storage deployment shows installed-base relevance',date:'2026-07-27',publisher:'Huawei',kind:'Customer reference',countries:['SA'],technology:'Data center',summary:'Huawei describes a storage deployment with Saudi service provider stc. The public reference demonstrates installed-base relevance; scope and commercial value are not disclosed.',implication:'Test where storage, data resilience and network modernization are evaluated together.',url:'https://e.huawei.com/en/case-studies/global/2026/stc-oceanstor',group:'stc-storage'},
 {id:'sa-cloudcampus',title:'Southern Africa SaaS campus launch frames operations as an offer',date:'2026-07-23',publisher:'Huawei Enterprise Southern Africa',kind:'Regional launch',countries:['ZA'],technology:'Enterprise campus',summary:'Huawei’s Southern Africa material presents a SaaS campus model spanning operations, security and lifecycle management. Launch messaging does not prove field performance.',implication:'Compare the operating model, access policy, data residency, partner delivery and lifecycle economics.',url:'https://www.linkedin.com/posts/huawei-enterprise-southern-africa_cloudcampus-saas-networking-activity-7351909849000000000-aaaa',group:'sa-campus'},
 {id:'apac-fabric',title:'APAC launches repeat AI-ready fabric narrative',date:'2026-08-13',publisher:'Huawei Enterprise APAC',kind:'Regional launch',countries:['ID','MY'],technology:'Data center',summary:'Huawei APAC campaign material links AI operations with a fabric designed to support AI workloads. Several posts describe one regional launch rather than independent customer wins.',implication:'Validate operations on mixed estates and lossless performance under real workloads.',url:'https://e.huawei.com/en/news/2026/apac-ai-ready-networking',group:'apac-fabric'},
 {id:'apac-xinghe',title:'Xinghe Intelligent Network messaging targets autonomous operations',date:'2026-08-13',publisher:'Huawei Enterprise APAC',kind:'Product announcement',countries:['ID','MY'],technology:'Enterprise campus',summary:'Huawei’s APAC material positions Xinghe as a platform for intelligent network operations. Product messaging is not evidence of general availability in every market.',implication:'Ask for deployment boundaries, telemetry integrations and operational proof points.',url:'https://e.huawei.com/en/news/2026/xinghe-intelligent-network-apac',group:'apac-fabric'},
 {id:'china-agentic-infra',title:'China Agentic Infra launch packages infrastructure, models and agents',date:'2026-06-05',publisher:'Huawei',kind:'Platform launch',countries:['CN'],technology:'Full-stack AI',summary:'Huawei’s China Agentic Infra launch positions infrastructure, models and agents as a coordinated enterprise stack. Availability and beta status vary by component.',implication:'Find who owns the AI architecture and budget, then position networking, security and observability in that decision.',url:'https://www.huawei.com/cn/news/2026/6/agentic-infra',group:'cn-agentic'},
 {id:'china-codearts',title:'CodeArts adds developer-agent capabilities in China',date:'2026-08-25',publisher:'Huawei Cloud',kind:'Product announcement',countries:['CN'],technology:'Full-stack AI',summary:'Huawei Cloud announced new CodeArts developer-agent capabilities. This is adjacent to network competition but relevant to a broader agentic-cloud conversation.',implication:'Watch developer platform pull-through into infrastructure and security decisions.',url:'https://www.huaweicloud.com/intl/en-us/news/20260825160000001.html',group:'cn-codearts'},
 {id:'germany-hpc',title:'European HPC research keeps Huawei AI infrastructure visible',date:'2026-06-25',publisher:'Research consortium / Huawei',kind:'Research partnership',countries:['DE'],technology:'Data center',summary:'A European research collaboration references Huawei infrastructure in an HPC and AI context. Research participation should not be read as broad commercial deployment.',implication:'Separate research credibility from production enterprise proof and procurement eligibility.',url:'https://www.huawei.com/en/news/2026/6/europe-hpc-ai-research',group:'eu-hpc'},
 {id:'france-aidc',title:'France AI data-center facility adds infrastructure context',date:'2026-06-02',publisher:'Huawei',kind:'Facility update',countries:['FR'],technology:'Data center',summary:'Huawei described an AI-oriented data-center facility in France. Public material does not establish market share or customer displacement.',implication:'Monitor sovereign compute requirements and the role of network fabric in AI facilities.',url:'https://www.huawei.com/en/news/2026/6/ai-data-center-france',group:'fr-aidc'},
 {id:'malaysia-waic',title:'Malaysia ecosystem activity connects Huawei AI and partner conversations',date:'2026-09-09',publisher:'Huawei Malaysia',kind:'Ecosystem event',countries:['MY'],technology:'Full-stack AI',summary:'Huawei Malaysia event material links AI ecosystem partners and enterprise infrastructure conversations. Event participation is not proof of a customer win.',implication:'Identify the buying center behind ecosystem commitments and partner-led deployments.',url:'https://www.huawei.com/my/news/2026/9/waic-malaysia',group:'my-ecosystem'},
 {id:'singapore-ap5g',title:'Singapore service-provider roundtable keeps network evolution in view',date:'2026-06-30',publisher:'Huawei Enterprise Singapore',kind:'Ecosystem event',countries:['SG'],technology:'Service provider',summary:'A Singapore roundtable with service-provider participants discussed 5G and network evolution. The evidence does not disclose a new commercial award.',implication:'Track where service-provider modernization overlaps with enterprise security and automation.',url:'https://e.huawei.com/sg/news/2026/5g-roundtable',group:'sg-roundtable'},
 {id:'rain-network',title:'Rain reference keeps Huawei relevance visible in South Africa',date:'2026-07-07',publisher:'Huawei',kind:'Customer reference',countries:['ZA'],technology:'Service provider',summary:'Huawei references a network deployment with South African operator Rain. The public case describes planned scale; completion and value are not disclosed.',implication:'Use installed-base context to test adjacent campus, security and AI-fabric opportunities.',url:'https://www.huawei.com/en/case-studies/global/2026/rain-network',group:'rain'},
 {id:'nigeria-ncce',title:'Nigeria NCCE cooperation expands Huawei AI ecosystem visibility',date:'2026-07-31',publisher:'NCCE / Huawei',kind:'Cooperation',countries:['NG'],technology:'Full-stack AI',summary:'Nigeria’s education and technology ecosystem cooperation with Huawei adds public-sector context. It is not evidence of an infrastructure order.',implication:'Watch skills, cloud and public-sector programs for downstream infrastructure pull-through.',url:'https://www.ncce.gov.ng/news/huawei-cooperation-2026',group:'ng-ncce'},
 {id:'colombia-fabric',title:'Latin America AI-ready networking launch raises regional visibility',date:'2026-08-05',publisher:'Huawei Enterprise Latin America',kind:'Regional launch',countries:['CO','BR','MX'],technology:'Data center',summary:'Huawei regional material presents an AI-ready networking fabric for Latin America. Launch scope does not disclose independent country wins.',implication:'Test local buyer evidence and whether fabric attaches to campus or AI projects.',url:'https://e.huawei.com/latinamerica/news/2026/ai-ready-networking',group:'latam-fabric'},
 {id:'mexico-academy',title:'Mexico university program brings AI infrastructure into education context',date:'2026-06-16',publisher:'Huawei / UJED',kind:'Academic reference',countries:['MX'],technology:'Full-stack AI',summary:'Huawei material describes an academic AI and digital-infrastructure program with UJED. Academic reference is not equivalent to a broad commercial enterprise win.',implication:'Watch university compute projects for network, security and lifecycle attach.',url:'https://www.huawei.com/mx/news/2026/6/ujed-ai',group:'mx-ujed'},
 {id:'brazil-cptm',title:'Brazil public-sector tender illustrates mixed-vendor maintenance context',date:'2026-07-08',publisher:'CPTM tender record',kind:'Tender context',countries:['BR'],technology:'Political',summary:'A Brazilian public tender references maintenance and infrastructure scope involving multiple vendors. It is not treated as a new Huawei hardware award.',implication:'Separate maintenance exposure from new-build displacement when qualifying public-sector accounts.',url:'https://www.cptm.sp.gov.br/licitacoes/2026',group:'br-cptm'},
 {id:'us-trial',title:'US legal proceedings add a current geopolitical watch item',date:'2026-09-08',publisher:'Reuters',kind:'Legal / political',countries:['CN'],technology:'Political',summary:'Reuters reports jury-selection activity in a US case involving Huawei-related allegations. Proceedings and allegations are not findings of guilt.',implication:'Keep legal risk, export policy and account-specific procurement analysis separate.',url:'https://www.reuters.com/world/us/jury-selection-huawei-case-2026-09-08/',group:'us-case'},
 {id:'eu-supply-chain',title:'EU supply-chain proposals remain policy context, not a current win/loss',date:'2026-01-20',publisher:'European policy reporting',kind:'Policy background',countries:['DE','FR','ES'],technology:'Political',summary:'European proposals on telecom supply-chain resilience provide dated policy context. They do not establish a uniform product ban or country outcome.',implication:'Assess the relevant jurisdiction, sector and transaction rather than applying a blanket assumption.',url:'https://digital-strategy.ec.europa.eu/en/policies/secure-connectivity',group:'eu-policy'},
 {id:'bis-ascend-background',title:'US export-control guidance is background for accelerator diligence',date:'2025-05-13',publisher:'US BIS',kind:'Policy background',countries:['CN','EG'],technology:'Political',summary:'US guidance concerning advanced computing and semiconductor controls is retained as background for AI accelerator diligence, not as a current country event.',implication:'Validate the product, end user, route and transaction-specific legal position.',url:'https://www.bis.gov/press-release/commerce-strengthens-export-controls-advanced-computing',group:'bis'}
];
export const levelValue=(l:Level)=>({High:3,Medium:2,Low:1,Unassessed:0}[l]);
export function current(a:Article){return a.date>='2026-06-01'&&a.date<='2026-09-12'&&a.kind!=='Policy background';}
export function formatDate(d:string){return new Date(d+'T12:00:00Z').toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});}
export function search(query:string){const terms=query.toLowerCase().trim().split(/\s+/).filter(Boolean);return articles.filter(a=>{const c=a.countries.map(x=>countries.find(y=>y.code===x)?.name||x).join(' ');const t=[a.title,a.summary,a.implication,a.publisher,a.kind,a.technology,c].join(' ').toLowerCase();return terms.every(x=>t.includes(x));});}
export const trends=[
 {id:'campus',title:'Campus competition is becoming a platform decision',technology:'Enterprise campus',stage:'Expanding',summary:'Southern Africa’s SaaS campus launch and APAC’s campus/security campaign suggest a broader conversation about operations, consumption and channel reach.',implication:'Compare automation, access policy, data residency, partner delivery and lifecycle cost.',caution:'Launch materials do not prove field performance or general availability.',evidence:['sa-cloudcampus','apac-xinghe']},
 {id:'fabric',title:'AI4NET and NET4AI travel together',technology:'Data center',stage:'Regional rollout',summary:'Southern Africa, Latin America and APAC releases repeat a common fabric narrative: AI to operate networks, and networks to support AI workloads.',implication:'Validate operations on mixed estates, lossless performance and recovery under real workloads.',caution:'Regional launches are not independent customer adoption studies.',evidence:['sa-cloudcampus','apac-fabric','colombia-fabric']},
 {id:'fullstack',title:'Local cloud is becoming a route to agentic AI',technology:'Full-stack AI',stage:'Emerging',summary:'China’s Agentic Infra launch and Nigeria’s local agentic-cloud proposition package infrastructure, models and agents into a broader enterprise offer.',implication:'Find who owns the AI architecture and budget, then position networking, security and observability in that decision.',caution:'Distinguish beta platforms, commercial services and country-specific availability.',evidence:['china-agentic-infra','nigeria-agentic-cloud','china-codearts']},
 {id:'silicon',title:'Ascend bids can influence surrounding infrastructure',technology:'AI silicon',stage:'Watch closely',summary:'The reported Egypt proposal shows how accelerator supply can shape a complete AI deployment beyond the chip purchase itself.',implication:'Monitor fabric, interconnect, security and integration scope attached to accelerator-led bids.',caution:'A reported proposal is not an award, delivery confirmation or benchmark.',evidence:['egypt-ai-bid','china-agentic-infra','bis-ascend-background']},
 {id:'political',title:'Technology decisions intersect with geopolitical constraints',technology:'Political',stage:'Persistent',summary:'Egypt bid reporting and September US proceedings are current watch items. EU proposals and BIS guidance are separately dated policy context.',implication:'Build account-specific risk assessments using the relevant jurisdiction, sector and transaction.',caution:'Proposals, charges and guidance have different legal meanings.',evidence:['egypt-ai-bid','us-trial','eu-supply-chain','bis-ascend-background']}
];
